#if ! defined(MACRO)
#error "MACRO not defined"
#endif

MACRO(APP_CREATE_NODE)
MACRO(APP_CREATE_PUBLISHER)
MACRO(APP_SUBSCRIBE)

MACRO(APP_PUBLISH)
MACRO(APP_SUB_RECV_CB)

MACRO(APP_SYNC)

MACRO(RMW_SEND_INTEREST_SYNC_BEGIN)
MACRO(RMW_SEND_INTEREST_SYNC_END)

MACRO(RMW_SEND_INTEREST_DATA_BEGIN)
MACRO(RMW_SEND_INTEREST_DATA_END)

MACRO(RMW_RECV_INTEREST_BEGIN)
MACRO(RMW_RECV_INTEREST_SYNC)
MACRO(RMW_RECV_INTEREST_DATA)
MACRO(RMW_RECV_INTEREST_END)

MACRO(RMW_SEND_NDNDATA_SYNC_BEGIN)
MACRO(RMW_SEND_NDNDATA_SYNC_END)

MACRO(RMW_RECV_NDNDATA_SYNC_BEGIN)
MACRO(RMW_RECV_NDNDATA_SYNC_END)

MACRO(RMW_SEND_NDNDATA_DATA_BEGIN)
MACRO(RMW_SEND_NDNDATA_DATA_END)

MACRO(RMW_RECV_NDNDATA_DATA_BEGIN)
MACRO(RMW_RECV_NDNDATA_DATA_END)

MACRO(RMW_NDN_APP_EXPRESS_SYNC_INTEREST)
MACRO(RMW_NDN_APP_EXPRESS_DATA_INTEREST)

MACRO(RMW_NDN_DATA_CREATE_BEFORE)
MACRO(RMW_NDN_DATA_CREATE_AFTER)

MACRO(RMW_NDN_APP_PUT_DATA_DATA)
MACRO(RMW_NDN_APP_PUT_SYNC_DATA)

MACRO(AT86RF2XX_FB_READ)
MACRO(AT86RF2XX_TX_EXEC)
MACRO(AT86RF2XX_TX_LOAD)
