include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := nucleo32-f031

FEATURES_REQUIRED = periph_usb_dev

USEMODULE += shell
USEMODULE += xtimer
USEMODULE += usb_dev_core

include $(RIOTBASE)/Makefile.include
